### ISSUE TITLE
Slow map loading.

### ISSUE THREAD

**Issue by ickobombata** [angelinn/TramlineFive.Xamarin#3]
## Current Behavior
The map is loaded after few seconds
## Expected Behavior
The map is loaded after few miliseconds.
## Steps to Reproduce
Open the application
## Operating system
Windows 10.

**Comment by angelinn** [comment]
Hello @ickobombata, 
Thank you for your contribution.

The maps that the application is using need to be downloaded from the [OSM tile servers](https://wiki.openstreetmap.org/wiki/Tile_servers) every time you open the application, this is what causes the loading behavior ot 1-3 seconds.

Therefore, a slower internet connection would result in slower loading times (which I assume is your case). I am having a good connection right now and having loading time of less than a second, which is also the way google maps works.

A solution is caching the maps offline as *.mbtiles file, which **could** resolve in faster loading times, but maps would still need to be read from the disk.

This would result in 25mb bigger application, because of the database with the Sofia tiles.

I am currently researching about how can this be done and an implementation might come in one of the next versions of the application.
If you have any suggestions, please feel free to share them.

**Comment by angelinn** [comment]
With update of Xamarin Forms, mapsui and setting home location the maps now load instantly. Feel free to comment after testing.
